site_name: Async behavior tree
repo_url: https://github.com/geronimo-iia/async-btree
repo_name: geronimo-iia/async-btree
docs_dir: docs
site_dir: site

theme:
  name: "material"
  features:
    - navigation.tracking
    - navigation.path
    - navigation.instant
    - navigation.tabs
    - navigation.indexes

plugins:
  - search
  - include-markdown
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            docstring_style: google

nav:
  - Home: index.md
  - Concepts: concepts.md
  - Tutorial: tutorial.md
  - API Reference: reference/
  - Changelog: changelog.md
  - Contributing: contributing.md
  - License: license.md
  - Code of Conduct: code_of_conduct.md
  - GitHub: https://github.com/geronimo-iia/async-btree
