name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.18"
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: make install 
    - name: Check Python package
      run: uv run poe check
