name: Upload Python Package

on:
  release:
    types: [created]

env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: make install 
      # poetry install --no-interaction
    - name: Check Python package
      run: make check
    - name: Test Python package
      run: make test
    - name: Build Python package and publish to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}

