name: Upload Python Package

on:
  release:
    types: [created]

env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Poetry
      run: |
        curl -fsS -o get-poetry.py https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
        python get-poetry.py -y
        rm -f get-poetry.py
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: make install 
      # poetry install --no-interaction
    - name: Check Python package
      run: make check test 
    - name: Build Python package and publish to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_TOKEN }}

