on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release

# IMPORTANT: this permission is mandatory for Trusted Publishing and deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    environment: pypi
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install uv and set up python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.5.18"
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install 
      - name: Build and publish to pypi
        run: uv run poe publish
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Build and publish Documentation
        run: |
            uv run poe docs
            uv run poe docs-publish
