on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release
env:
  POETRY_VIRTUALENVS_CREATE: false

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    # IMPORTANT: this permission is mandatory for Trusted Publishing
    permissions:
      id-token: write
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.18"    
      - name: Install dependencies
        run: make install 
      - name: Build and publish to pypi
        run: uv run poe publish
      - name: Build and publish Documentation
        run: |
          uv run poe docs
          uv run poe docs-publish
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
