on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    environment: pypi
    # IMPORTANT: this permission is mandatory for Trusted Publishing and deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv and set up python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.18"
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install 
      - name: Build and publish to pypi
        run: uv run poe publish
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Build and publish Documentation
        run: |
            uv run poe docs
            uv run poe docs-publish
